### ISSUE TITLE
which version is ready for production

### ISSUE THREAD

**Issue by jarcn** [FeatureProbe/FeatureProbe#283]
现在有哪个版本能在生产环境中使用吗？
1000万用户的体量具体应该如何配置机器资源

**Comment by gangb-tech** [comment]
**To this question, we need more information in order to provide specific recommendations:**

1、What type of application do you have? For example, is it a social network, an e-commerce platform, or something else?

2、What are the main usage scenarios? Are you conducting A/B testing or using a canary deployment process?

3、What type of client are you using? Is it a client or server?

**Please feel free to contact us to obtain detailed information on production practices.**
<img src="https://raw.githubusercontent.com/FeatureProbe/FeatureProbe/main/pictures/Wechat0715.png" width = "250" />
